# Generated by Django 4.1.3 on 2022-12-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("image", models.TextField(blank=True, default="", null=True)),
                (
                    "image_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("paragraphs", models.TextField(blank=True, default="", null=True)),
                ("publish_time", models.DateTimeField()),
                (
                    "author_name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "newsWebsiteName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
